server:
   port: 6401
      
debug: false

spring:
   application:
      name: ideahut-springboot-central
   servlet:
      multipart:
         max-file-size: 256MB
         max-request-size: 256MB
   main:
      banner-mode: "off"
   
   datasource:
      hikari:
         connection-timeout: "10000"
         minimum-idle: "10"
         maximum-pool-size: "10"
         idle-timeout: "5000"
         max-lifetime: "1000"
         auto-commit: "true"
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      jdbc-url: "jdbc:mysql://localhost:3306/admin_central?createDatabaseIfNotExist=true&autoReconnect=true"
      username: "<username>"
      password: "<password>"
   jpa:
      open-in-view: false
      properties:
         hibernate:
            hbm2ddl:
               auto: update
               #auto: none
            show_sql: true
            #generate_statistics: true
            audit_identifier: "admin_central"

app:
   loggingError: true
   adminFile: "{user.dir}/extras/admin.zip"
   
   cors:
      "Access-Control-Allow-Credentials": "true"
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "*"
      "Access-Control-Max-Age": "360"
      "Access-Control-Allow-Headers": "*"
      "Access-Control-Expose-Headers": "*"
                     
   ignored-handler-classes:
      - org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController
   
   expiry:
      auth: 1800
      module: 1800
      token: 60

   task:      
      threadNamePrefix: "TASK"
      corePoolSize: 2
      maxPoolSize: 8
      waitForJobsToCompleteOnShutdown: true
      allowCoreThreadTimeOut: true
         
   redis:
      common:
      type: 1
      testOnStartup: true
      standalone:
         host: 127.0.0.1
         port: 6379
         password: "<password>"
         database: 0
         
   resource:
      location: "{user.dir}/extras/resource/"
      redirectParameter: "_next_"
      path: "/ui"
      allowedPaths:
         - "css"
         - "fonts"
         - "icons"
         - "img"
         - "js"
   
   multimedia:
      #url: "http://localhost:6401/mm"
      url: "/mm"
      path: "/mm"
      location: "{user.dir}/multimedia/"
      
   grid:
      account: "{user.dir}/extras/account.json"
      project: "{user.dir}/extras/project.json"
      module: "{user.dir}/extras/module.json"
      redirect: "{user.dir}/extras/redirect.json"
         
logging:
   file:
      name: "./logs/ideahut-springboot-3x-admin-central.log"
   pattern:
      console: '%d %p [%X{traceId}] %F\(%M:%L\) : %msg%n'
      file: '%d %p [%X{traceId}] %F\(%M:%L\) : %msg%n'
   level:
      org:
         hibernate: INFO
         springframework: INFO
      redis:
         clients:
            jedis:
               JedisFactory: OFF
      com:
         fasterxml:
            jackson:
               dataformat:
                  xml: OFF
