server:
   port: 6401
      
debug: false

#
# SPRING
#
spring:
   application:
      name: ideahut-springboot-central
   servlet:
      multipart:
         max-file-size: 256MB
         max-request-size: 256MB
   main:
      banner-mode: "off"
   jpa:
      open-in-view: false

#
# CONFIG
#
config:
   waitAllBeanConfigured: true
   logAllError: true
   adminFile: "{user.dir}/extras/admin.zip"
   
   #
   # DATASOURCE
   #
   datasource:
      driverClassName: "<DRIVER>"
      jdbcUrl: "<JDBC-URL>"
      username: "<USERNAME>"
      password: "<PASSWORD>"
      connectionTimeout: 15000
      minimumIdle: 10
      maximumPoolSize: 10
      idleTimeout: 600000
      maxLifetime: 1800000
      poolName: "AdminCentralDatasourcePool"
   
   #
   # HIBERNATE
   #
   hibernate:
      hbm2ddl:
         auto: update
         #auto: none
      show_sql: true
      #generate_statistics: true
      audit_identifier: admin_central
      jdbc:
         lob:
            non_contextual_creation: true 
   
   #
   # FOREIGN KEY
   #   
   foreignKey:
      enableExecution: true
      dropBeforeCreate: true
      onUpdateAction: true 
   
   #
   # AUDIT
   #
   audit:
      rejectNonAuditEntity: true
      properties:
         generate:
            table: true
         enable:
            audit: true
         table:
            prefix: "_a_"

   #
   # FILTER
   #   
   filter:
      traceEnable: true
      enableTimeResult: true
      corsHeaders:
         "Access-Control-Allow-Credentials": "true"
         "Access-Control-Allow-Origin": "*"
         "Access-Control-Allow-Methods": "*"
         "Access-Control-Max-Age": "3600"
         "Access-Control-Allow-Headers": "*"
         "Access-Control-Expose-Headers": "*"
   
   #
   # EXPIRY      
   #
   expiry:
      auth: 
         unit: MINUTES
         value: 30
      module: 
         unit: MINUTES
         value: 30
      token: 
         unit: MINUTES
         value: 60
   
   #
   # TASK
   #
   task:      
      threadNamePrefix: "TASK"
      corePoolSize: 8
      maxPoolSize: 32
      waitForJobsToCompleteOnShutdown: true
      allowCoreThreadTimeOut: true
   
   #
   # REDIS
   #
   redis:
      type: 0
      standalone:
         host: "<HOST>"
         port: "<PORT>"
         password: "<PASSWORD>"
         database: 0 
   
   #
   # WEB      
   #
   web:
      path: "/ui"
      title: "Central"
      location: "{user.dir}/extras/web/"
      redirectParameter: "_next_"
      timeout: 60
      language: "en"
      debug: true
      allowedPaths:
         - "assets"
         - "icons"
         - "index.html"
      color:
         header: "linear-gradient(180deg, rgb(188, 14, 49) 0%, rgba(15, 142, 231, 1) 100%)"
         title: "gold"
         primary: ""
         secondary: ""
         accent: ""
         dark: ""
         positive: ""
         negative: ""
         info: ""
         warning: ""
   
   #
   # MULTIMEDIA
   #
   multimedia:
      url: "/mm"
      path: "/mm"
      location: "{user.dir}/multimedia/"
   
   #
   # GRID   
   #
   grid:
      account: "{user.dir}/extras/grid/account.yaml"
      project: "{user.dir}/extras/grid/project.yaml"
      module: "{user.dir}/extras/grid/module.yaml"
      redirect: "{user.dir}/extras/grid/redirect.yaml"

#
# LOGGING         
#
logging:
   file:
      name: "./logs/ideahut-springboot-central.log"
   pattern:
      console: '%d %p [%X{traceId}] %F\(%M:%L\) : %msg%n'
      file: '%d %p [%X{traceId}] %F\(%M:%L\) : %msg%n'
   level:
      org:
         hibernate: INFO
         springframework: INFO
      redis:
         clients:
            jedis:
               JedisFactory: OFF
      com:
         fasterxml:
            jackson:
               dataformat:
                  xml: OFF
