server:
   port: 6401
      
debug: false

spring:
   application:
      name: ideahut-springboot-central
   servlet:
      multipart:
         max-file-size: 256MB
         max-request-size: 256MB
   main:
      banner-mode: "off"
   
   datasource:
      hikari:
         connection-timeout: "10000"
         minimum-idle: "10"
         maximum-pool-size: "10"
         idle-timeout: "5000"
         max-lifetime: "1000"
         auto-commit: "true"
      driver-class-name: "<DRIVER>"
      jdbc-url: "<URL>"
      username: "<USERNAME>"
      password: "<PASSWORD>"
   jpa:
      properties:
         hibernate:
            hbm2ddl:
               auto: update
               #auto: none
            show_sql: true
            #generate_statistics: true
            audit_identifier: "admin_central"
            jdbc:
               lob:
                  non_contextual_creation: true

app:
   loggingError: true
   adminFile: "{user.dir}/extras/admin.zip"
   
   cors:
      "Access-Control-Allow-Credentials": "true"
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "*"
      "Access-Control-Max-Age": "360"
      "Access-Control-Allow-Headers": "*"
      "Access-Control-Expose-Headers": "*"
                     
   ignored-handler-classes:
      - org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController
   
   expiry:
      auth: 
         unit: MINUTES
         value: 30
      module: 
         unit: MINUTES
         value: 30
      token: 
         unit: MINUTES
         value: 60

   task:      
      threadNamePrefix: "TASK"
      corePoolSize: 8
      maxPoolSize: 32
      waitForJobsToCompleteOnShutdown: true
      allowCoreThreadTimeOut: true

   redis:
      type: 0
      standalone:
         host: "<HOST>"
         port: "<PORT>"
         password: "<PASSWORD>"
         database: 0 
         
   web:
      title: "Central"
      location: "{user.dir}/extras/web/"
      redirectParameter: "_next_"
      timeout: 60
      language: "en"
      debug: false
      allowedPaths:
         - "assets"
         - "icons"
   
   multimedia:
      #url: "http://localhost:6401/mm"
      url: "/mm"
      path: "/mm"
      location: "{user.dir}/multimedia/"
      
   grid:
      account: "{user.dir}/extras/grid/account.yaml"
      project: "{user.dir}/extras/grid/project.yaml"
      module: "{user.dir}/extras/grid/module.yaml"
      redirect: "{user.dir}/extras/grid/redirect.yaml"
         
logging:
   file:
      name: "./logs/ideahut-springboot-central.log"
   pattern:
      console: '%d %p [%X{traceId}] %F\(%M:%L\) : %msg%n'
      file: '%d %p [%X{traceId}] %F\(%M:%L\) : %msg%n'
   level:
      org:
         hibernate: INFO
         springframework: INFO
      redis:
         clients:
            jedis:
               JedisFactory: OFF
      com:
         fasterxml:
            jackson:
               dataformat:
                  xml: OFF
